# Generated by Django 3.2.12 on 2022-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Ready'), (4, 'Retrieved'), (5, 'Canceled')], default=1),
        ),
    ]
