# Generated by Django 3.2.12 on 2022-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='component', to='menu.Component'),
        ),
    ]
